export const ORDER_AGENCY_PORT = Symbol('ORDER_AGENCY_PORT');
export const ORDER_NOTIFICATION_PORT = Symbol('ORDER_NOTIFICATION_PORT');
export const ORDER_USERS_PORT = Symbol('ORDER_USERS_PORT');
export const ORDER_SERVICES_PORT = Symbol('ORDER_SERVICES_PORT');
export const ORDER_AVAILABILITY_PORT = Symbol('ORDER_AVAILABILITY_PORT');
