export const BusinessErrorCode = {
  INSUFFICIENT_CREDIT: 'INSUFFICIENT_CREDIT',
  COLLECTION_ACTIVE_LIMIT_EXCEEDED: 'COLLECTION_ACTIVE_LIMIT_EXCEEDED',
  PAYMENT_INIT_FAILED: 'PAYMENT_INIT_FAILED',
  PAYMENT_TRANSACTION_NOT_FOUND: 'PAYMENT_TRANSACTION_NOT_FOUND',
  OLD_PASSWORD_INCORRECT: 'OLD_PASSWORD_INCORRECT',
  PHONE_ALREADY_BOUND: 'PHONE_ALREADY_BOUND',
  SERVICE_BLOCK_CONFLICT: 'SERVICE_BLOCK_CONFLICT',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  LAST_LOGIN_METHOD_REQUIRED: 'LAST_LOGIN_METHOD_REQUIRED',
} as const;

export type BusinessErrorCode = (typeof BusinessErrorCode)[keyof typeof BusinessErrorCode];
