export const AGENCY_SERVICES_PORT = 'AGENCY_SERVICES_PORT';
export const AGENCY_LINK_QUERY_PORT = 'AGENCY_LINK_QUERY_PORT';
export const AGENCY_AUTH_PORT = 'AGENCY_AUTH_PORT';
export const AGENCY_SYSTEM_CONFIG_PORT = 'AGENCY_SYSTEM_CONFIG_PORT';
